const mongoose=require('mongoose');
const orderItem=mongoose.Schema({
    pizzaItem:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'pizzaItem',
    },
    userId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'User'
    },
    quantity:{
        type:Number,
    },
    base:{
      type:mongoose.Schema.Types.ObjectId,
        ref:'pizzaBase'  
    },
    chesse:{
      type:mongoose.Schema.Types.ObjectId,
        ref:'pizzaChesse' 
    },
    sauce:{
      type:mongoose.Schema.Types.ObjectId,
        ref:'pizzaSauce'  
    },
    veg:{
      type:mongoose.Schema.Types.ObjectId,
        ref:'pizzaVeg'  
    },
    status:{
      type:String,
      default:"Update"
    },
    payment_id:{
      type:String,
    },
    order_id:{
      type:String,
    },
    payment_signature:{
      type:String,
    },
    payment_status:{
      type:String,
      default:"Failed"
    },
    floor:{
      type:String,
    },
    area:{
      type:String,
    },
    city:{
      type:String,
    },
    pincode:{
      type:Number
    },
    price:{
      type:Number
    }
})
module.exports=mongoose.model("Order",orderItem)